---
page-layout: full
format:
  html:
    css: styles.css
    body-classes: publication-page
---



## Manuscripts Under Review

17\. **Dong, Y.**, Marandino, C. A., Dobashi, R., Ho, D. T., Rehder, G., Bittig, H. C., Karnatz, J., Sabbaghzadeh, B., Czerski H., & Engel, A. (2025). Mechanisms of air–sea CO₂ exchange in the central Baltic Sea. *Atmospheric Chemistry and Physics* (under review). Preprint: https://doi.org/10.5194/egusphere-2025-6095  

16\. Dobashi, R., Ho, D. T., **Dong, Y.**, Marandino, C. A., & Czerski, H. (2025). Air–sea gas exchange in the central Baltic Sea. *Geophysical Research Letters* (under review).  

15\. Ford, D. J., Shutler, J. D., Holding, T., Sims, R. P., Ashton, I., Woolf, D. K., Goddijn-Murphy, L., Bakker, D. C. E., Sabine, C., Merchant C. J., Embury O., **Dong, Y.**, & Wanninkhof, R. (2025). Recalculating the Surface Ocean CO₂ Atlas (SOCAT) to a sea surface temperature climate data record. *Scientific Data* (under review).  

14\. Yu, L., Josey, S., Bourassa, M., **Dong, Y.**, & Behrangi, A. (2025). Ocean–atmosphere fluxes of heat, moisture, momentum, aerosols, and gases. *Encyclopedia of Climate System Science* (under review).  

13\. **Dong, Y.**, Jähne, B., Woolf, D. K., Krall, K. E., Yang, M., Czerski, H., Liang, J., Brooks, I. M., McNeil, C. L., Wanninkhof, R., Ho, D. T., Atamanchuk, D., & Marandino, C. A. (2025). The role of bubbles in air–sea gas exchange: A critical review. ***Reviews of Geophysics*** (under review). Preprint: https://doi.org/10.22541/essoar.175611263.31332921/v1  

12\. Yin, H., **Dong, Y.**, & Lu, X. (2025). Assessing gas transfer velocity: The impact of ignoring skin temperature corrections. *Limnology and Oceanography Letters* (under review).  

11\. **Dong, Y.**, Yang, M., & Bell, T. G. (2022). Advancements in air–sea gas transfer velocity estimations from eddy covariance flux measurements. In *Cross-linking lab and field measurements and numerical modelling to identify and quantify the mechanisms of air–sea gas transfer* (under review).

## Peer-reviewed Publications

**2025**

10\. **Dong, Y.**, Yang, M., Bell, T. G., Marandino, C. A., & Woolf, D. K. (2025). Asymmetric bubble-mediated gas transfer enhances global ocean CO₂ uptake. ***Nature Communications***, 16, 10595.  


**2024**

9\. **Dong, Y.**, Bakker, D. C. E., Bell, T. G., Yang, M., Landschützer, P., Hauck, J., Rödenbeck, C., Kitidis, V., Bushinsky, S. M., & Liss, P. S. (2024). Direct observational evidence of strong CO₂ uptake in the Southern Ocean. ***Science Advances***, 10(30), eadn5781.  

8\. **Dong, Y.**, Bakker, D. C. E., & Landschützer, P. (2024). Accuracy of ocean CO₂ uptake estimates at risk due to reduced data collection. *Geophysical Research Letters*, 51, e2024GL108502.  

7\. Yang, M., Moffat, D., **Dong, Y.**, & Bidlot, J. R. (2024). Deciphering the variability in air–sea gas transfer due to sea state and wind history. *PNAS Nexus*, pgae389.  

6\. Workman, E., Fisher, R. E., France, J. L., Linse, K., Yang, M., Bell, T. B., **Dong, Y.**, & Jones, A. E. (2024). Methane emissions from seabed to atmosphere in polar oceans revealed by direct methane flux measurements. *Journal of Geophysical Research: Atmospheres*, 129, e2023JD040632.  


**2022**

5\. **Dong, Y.**, Bakker, D. C. E., Bell, T. G., Huang, B., Landschützer, P., Liss, P. S., & Yang, M. (2022). Update on the temperature corrections of global air–sea CO₂ flux estimates. *Global Biogeochemical Cycles*, 36(9), e2022GB007360.  

4\. Yang, M., Bell, T. G., Bidlot, J. R., Blomquist, B. W., Butterworth, B. J., **Dong, Y.**, Fairall, C. W., Landwehr, S., Marandino, C. A., Miller, S. D., & Saltzman, E. S. (2022). Global synthesis of air–sea CO₂ transfer velocity estimates from ship-based eddy covariance measurements. *Frontiers in Marine Science*, 9, 826421.  


**2021**

3\. **Dong, Y.**, Yang, M., Bakker, D. C. E., Liss, P. S., Kitidis, V., Brown, I., Chierici, M., Fransson, A., & Bell, T. G. (2021). Near-surface stratification due to ice melt biases Arctic air–sea CO₂ flux estimates. *Geophysical Research Letters*, 48(22), 1–10.  

2\. **Dong, Y.**, Yang, M., Bakker, D. C. E., Kitidis, V., & Bell, T. G. (2021). Uncertainties in eddy covariance air–sea CO₂ flux measurements and implications for gas transfer velocity parameterisations. *Atmospheric Chemistry and Physics*, 21(10), 8089–8110.  


**2018**

1\. Zhao, D., Jia, N., & **Dong, Y.** (2018). Relationship between turbulent energy dissipation and gas transfer through the air–sea interface. *Tellus B: Chemical and Physical Meteorology*, 70(1), 1–11.
